defaults:
  - scope:
      path: ""
    values:
      layout: default
collections_dir: "."
collections:
  poetry:
    output: true
  prose:
    output: true
  essays:
    output: true
  projects:
    output: true
  achievements:
    output: true
