backend:
  name: github
  repo: anshuman3kdka/anshuman3kdka.github.io
  branch: main
  client_id: Ov23li6QdMcxjp1u3cBw

publish_mode: simple

collections:
  - name: poetry
    label: Poetry
    folder: poetry
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
