backend:
  name: github
  repo: anshuman3kdka/anshuman3kdka.github.io
  branch: main
  auth_type: pkce
  auth_endpoint: https://YOUR-OAUTH-APP.netlify.app/auth

local_backend: true

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "poetry"
    label: "Poetry"
    folder: "_poetry"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string", default: "Anshuman3kdka" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "prose"
    label: "Prose"
    folder: "_prose"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string", default: "Anshuman3kdka" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "essays"
    label: "Essays"
    folder: "_essays"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string", default: "Anshuman3kdka" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "projects"
    label: "Projects"
    folder: "_projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string", default: "Anshuman3kdka" }
      - { label: "Body", name: "body", widget: "markdown" }
